version: "3"
services:
  php:
    user: apache
    build:
      context: ./docker/php
    depends_on:
      - database
      - mail
      - memcached
    ports:
      - ${PORT_WEB_APP:-8000}:8080
    volumes:
      - php:/var/www
      - ./docker/php/php.ini:/etc/php.ini
      - ./docker/php/httpd.conf:/etc/httpd/conf/httpd.conf
    working_dir: /var/www
    environment:
      # Synfony / ECCUBE
      - APP_ENV=${APP_ENV:-dev}
      - APP_DEBUG=${APP_DEBUG:-1}
      - DATABASE_URL=postgres://postgres@database/postgres
      - MAILER_URL=smtp://mail:1025
      # PostgreSQL
      - PGHOST=database
      - PGUSER=postgres
      # OS
      - TZ=Asia/Tokyo
      - LANG=C.UTF-8
      - LANGUAGE=en_US

  database:
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - ${PORT_PGSQL:-5432}:5432
    environment:
      - TZ=Asia/Tokyo
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS="--locale=ja_JP.utf8"

  mail:
    image: axllent/mailpit
    ports:
      - ${PORT_WEB_MAIL:-8025}:8025

  memcached:
    image: memcached:latest

  phppgadmin:
    image: bitnami/phppgadmin
    ports:
      - ${PORT_WEB_PHPPGADMIN:-8432}:8080
    environment:
      DATABASE_HOST: database
    depends_on:
      - database

volumes:
  database:
  php:
